### PR TITLE
fix: list protobufjs as direct dependency (#423)

### LINKED ISSUE #423: Usage with yarn v2 and PnP throws an error
#### Environment details

  - OS: windows
  - Node.js version: 14.5.0
  - npm version: 6.13.1
  - `@google-cloud/text-to-speech` version: 3.0.1

#### Steps to reproduce

  1. Use this package within a yarn 2 project with PnP enabled
  2. Use the package somewhere in your codebase and run it

following error is thrown:

```sh
Error: @google-cloud/text-to-speech tried to access protobufjs, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.

Required package: protobufjs (via "protobufjs/minimal")
```

### PR DESCRIPTION
**Pull request by DRoet**
- [x] Make sure to open an issue as a [bug/issue](https://github.com/googleapis/nodejs-text-to-speech/issues/new/choose) before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [x] Ensure the tests and linter pass
- [x] Code coverage does not decrease (if any source code was changed)
- [x] Appropriate docs were updated (if necessary)

Fixes #423 by listing protobufjs as direct dependency 🦕

### CODE REVIEW

**Comment by DRoet** [comment]
@googlebot I signed it!

**Review by JustinBeckwith — COMMENTED** [review]
Greetings, and thanks for the PR!  I am very confused on why this would be necessary though.  `protobufjs` is listed as an explicit dependency of `google-gax`, as you can see here:
https://github.com/googleapis/gax-nodejs/blob/master/package.json#L27

I have to think that if you're having resolution problems it's a bug with Yarn...  right?

**Comment by DRoet** [comment]
It's by design

The new yarn PnP functionality has a stricter module resolution that will prevent packages to require dependencies that they don't explicitly list (even if one of their other dependencies happens to depend on it)

**Comment by alexander-fenster** [comment]
Thanks @DRoet for reporting this. It's indeed a problem, but we'll better fix it in the place where we generate `protos/protos.js` and `protos/protos.d.ts` by depending on the `protobufjs` re-exported from `google-gax`. We really don't want to have an extra dependency here.

Fixing here: https://github.com/googleapis/gax-nodejs/pull/868

**Comment by DRoet** [comment]
@alexander-fenster sounds good, closing this in favor of that solution

**Pull request closed without merging**
