### PR TITLE
chore: bump version to 0.2.0

### PR DESCRIPTION
**Pull request by jkwlui**
Releasing v1beta1 regen (#27)

[Release draft](https://github.com/googleapis/nodejs-text-to-speech/releases/edit/untagged-9196260cb649acf7f414)

- [x] Tests and linter pass
- [x] Code coverage does not decrease (if any source code was changed)
- [x] Appropriate docs were updated (if necessary)

### CODE REVIEW

**Comment by kinwa91** [comment]
Alright, trying this again by following release note format from other repos :)

**Comment by kinwa91** [comment]
Rewritten the draft release :) @JustinBeckwith

**Comment by crwilcox** [comment]
I can't see the draft. We usually just paste the notes into the PR description.

**Review by JustinBeckwith — APPROVED** [review]
Much better!

**Pull request merged**
