### PR TITLE
docs(samples): updates effects profile sample

### PR DESCRIPTION
**Pull request by telpirion**
This pull request does the following:

- Updates the audioProfiles.js file so that it explicitly uses an array for `effectsProfileIds`.
- Changes the format of audioProfiles.js to look more like current Node.js samples.
- Simplifies the tests for audioProfiles.js (no need to test multiple hardware without checking audio quality).

### CODE REVIEW

**Comment by JustinBeckwith** [comment]
@telpirion 👋  cleaning up some PRs - is this still a thing?  Anything we can do to help?

**Comment by telpirion** [comment]
Yes, this is still a valid PR. Thank you for checking!

**Review by bcoe — APPROVED** [review]
You just need to run `npm run fix`.

**Comment by telpirion** [comment]
It looks like the docs test is failing on this URL:
`https://www.npmjs.org/package/@google-cloud/text-to-speech`

@bcoe Would you mind helping me out with this?

**Pull request merged**
